openapi: 3.0.3
info:
  title: Keep-Track API
  description: Keep-Track API
  version: 1.0.0

paths:
  /product:
    get:
      tags:
        - Product
      operationId: getProduct
      description: Returns the Product for the given barcode
      parameters:
        - name: barCode
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '500':
          description: Server error
    post:
      tags:
        - Product
      operationId: postProduct
      description: Adds new product to the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
        '500':
          description: Server error

components:
  schemas:
    Product:
      type: object
      properties:
        productName:
          type: string
        manufacturer:
          type: string
        barCode:
          type: string
