openapi: 3.0.3
info:
  title: Keep-Track API
  description: Keep-Track API
  version: 1.0.0

paths:
  /product:
    get:
      tags:
        - Product
      operationId: getProduct
      description: Returns the Product for the given id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
        '500':
          description: Server error
