server:
  port: 8001
  servlet:
    context-path: /api

management:
  server:
    port: 8002
  endpoints:
    web:
      exposure:
        include: '*, httptrace'

spring:
  application:
    name: Keep-Track
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/keep_track
    username: postgres
    password: pWnWXMJqqQFmLVGy7KmN
    driverClassName: org.postgresql.Driver
  liquibase:
    changeLog: classpath:/db/db.changelog-master.xml
    enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
springdoc:
  swagger-ui:
    path: /swagger

logging:
  file:
    name: keep-track.log
  pattern:
    console: '%date{"yyyy-MM-dd HH:mm:ss,SSS", Europe/Berlin} %-5level [%thread] %logger : %msg%n'
  level:
    root: info

keep-track:
  jwt-secret: ${JWT_SECRET}
  jwt-expiration-ms: 86400000 #1day